# Generated by Django 4.1.7 on 2023-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_choice_text_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Default Choice Text', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.CharField(default='Default Question Text', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
